### ISSUE TITLE
Module doesn't get activated

### ISSUE THREAD

**Issue by 963io** [peterzuger/bitstruct-micropython#2]
Hi!

I wanted to use this module in my micropython project based on esp32. I'm new to this, so please bear with me. So I've compiled micropython according to these instructions
https://warped3.substack.com/p/compiling-micropython-with-espressif?s=r
with one exception:
idf.py -DMODULE_BITSTRUCT_ENABLED=1 build

Now it compiles alright, but when I try to run it:
`>>> import bitstruct
>>> dir(bitstruct)
['__class__', '__name__', '__path__']`

So for some reason no functions are loaded. Could you please tell me why?

**Comment by peterzuger** [comment]
I am not familiar with Micropython on esp32, but looking at the [ESP32 Makefile](https://github.com/micropython/micropython/blob/66b5c4c770b0d7a9f07cdb31fce94edda2fe3c13/ports/esp32/Makefile). It seems like you are not setting `USER_C_MODULES` to the cmake file for this module.

```
git clone https://github.com/peterzuger/bitstruct-micropython.git
cd micropython/ports/esp32
idf.py -DUSER_C_MODULES=../../../bitstruct-micropython/micropython.cmake -DMODULE_BITSTRUCT_ENABLED=1 build
```

I was not able to verify that this works since I have not setup the ESP32 toolchain but if it does not work the st7789_mpy module from russhughes has a detailed explanation how to build for esp32.

https://github.com/russhughes/st7789_mpy
https://github.com/micropython/micropython/tree/master/ports/esp32

**Comment by 963io** [comment]
Hi, @peterzuger !

Sorry for long reply, tried to fix it myself. Unfortunately, still no luck. I've commented out
`#if defined(MODULE_BITSTRUCT_ENABLED) && MODULE_BITSTRUCT_ENABLED == 1`
and
`#endif defined(MODULE_BITSTRUCT_ENABLED) && MODULE_BITSTRUCT_ENABLED == 1`
Just in case. It compiles fine. In fact, I've added cexample module and ufastlz (one for test, second I need). 
I've chained them in micropython.cmake (in modules dir) like this:
`include(${CMAKE_CURRENT_LIST_DIR}/bitstruct/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ufastlz/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cexample/micropython.cmake)`
So, last 2 lines are fetched and compiled in. Now
`>>> import bitstruct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'bitstruct'`

**Comment by 963io** [comment]
Okay, silly me, documentation states
https://micropython-tve.readthedocs.io/en/latest/develop/cmodules.html
`Note that the exact method depends on the port as they have different structures. If not done correctly it will compile but importing will fail to find the module.`

So, apparently command line switches did not enabled it, but
`#define MODULE_BITSTRUCT_ENABLED (1)`
did the trick!
